{"uid":"91dfc43016d08d2c","name":"Invalid login -- @1.7 ","fullName":"Login Seafarer App Backend: Invalid login","historyId":"859a72d29a3e69b881461cfa7b05a9d8","time":{"start":1688315183914,"stop":1688315184223,"duration":309},"status":"failed","statusMessage":"AssertionError: Expected error: INVALID_PASSWORD. Actual error: TOO_MANY_ATTEMPTS_TRY_LATER : Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.\n","statusTrace":"  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"backend/behave/sf_app/steps/login_steps.py\", line 25, in receive_error_message\n    context.login_obj.CheckErrorMessage(context, error)\n  File \"/home/giorgos/all_repos/poseidon/backend/src/helpers/login_service.py\", line 62, in CheckErrorMessage\n    assert (\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected error: INVALID_PASSWORD. Actual error: TOO_MANY_ATTEMPTS_TRY_LATER : Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.\n","statusTrace":"  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"backend/behave/sf_app/steps/login_steps.py\", line 25, in receive_error_message\n    context.login_obj.CheckErrorMessage(context, error)\n  File \"/home/giorgos/all_repos/poseidon/backend/src/helpers/login_service.py\", line 62, in CheckErrorMessage\n    assert (\n","steps":[{"name":"When Enter email address \"georgegkiokas92@gmail.com\" and password \"<password>\" with status code \"400\"","time":{"start":1688315183915,"stop":1688315184220,"duration":305},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Then I should receive an error message stating \"INVALID_PASSWORD\"","time":{"start":1688315184221,"stop":1688315184222,"duration":1},"status":"failed","statusMessage":"AssertionError: Expected error: INVALID_PASSWORD. Actual error: TOO_MANY_ATTEMPTS_TRY_LATER : Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later.\n","statusTrace":"  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/giorgos/all_repos/poseidon/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"backend/behave/sf_app/steps/login_steps.py\", line 25, in receive_error_message\n    context.login_obj.CheckErrorMessage(context, error)\n  File \"/home/giorgos/all_repos/poseidon/backend/src/helpers/login_service.py\", line 62, in CheckErrorMessage\n    assert (\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true},{"name":"And I should not be logged in","time":{"start":1688315184223,"stop":1688315184223,"duration":0},"status":"skipped","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":3,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"tag","value":"login_tag_backend"},{"name":"feature","value":"Login Seafarer App Backend"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"comment","value":"Blank password"},{"name":"email","value":"georgegkiokas92@gmail.com"},{"name":"error","value":"INVALID_PASSWORD"},{"name":"password","value":"<password>"},{"name":"status_code","value":"400"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["login_tag_backend"]},"source":"91dfc43016d08d2c.json","parameterValues":["Blank password","georgegkiokas92@gmail.com","INVALID_PASSWORD","<password>","400"]}